version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/btc-controller"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/wallet-ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
